fx_version 'cerulean'
game 'gta5'
lua54 'yes'
author 'Bonezz'
description 'Bonezz Rx – item definitions and usage examples (requires manual integration with qb-core items)'
version '3.0.0'
shared_script 'items.lua'
client_script 'client.lua'
server_script 'server.lua'
