fx_version 'cerulean'
game 'gta5'
lua54 'yes'
author 'Bonezz'
description 'Corrupt Cops Lite – UC briefings with sting/intervention outcomes'
version '1.0.0'
shared_script 'config.lua'
client_script 'client.lua'
server_script 'server.lua'
