$schema: "https://raw.githubusercontent.com/tabarra/txAdmin-recipe-schemas/master/recipe.yaml"

name: "Bonezz Bangerz – Full Addon"
version: "2.0.1"
author: "mizterbonezzmusic"
description: |
  Plug-and-play deployment of Bonezz Bangerz server.
  Includes bonezz_min, bonezz_rx_loader, Bonezz Rx items, UC Blips v2, UC Safehouses, Corrupt Cops, and preloaded server.cfg.

server: "Bonezz Bangerz"

tasks:
  - action: download_github
    src: "mizterbonezzmusic/BonezzBangerz_PlugAndPlayRepo"
    ref: "main"
    dest: "./"
