$schema: "https://raw.githubusercontent.com/tabarra/txAdmin-recipe-schemas/master/fxmanifest/recipe.yaml"
name: "Bonezz Bangerz – Full Addon"
version: "1.5.0"
author: "mizterbonezzmusic"
description: "Deploys Bonezz Bangerz resources with placeholders and server.cfg."
server: "Bonezz Bangerz"

tasks:
  - action: download_github
    src: "mizterbonezzmusic/BonezzBangerz_PlugAndPlayRepo"
    ref: "main"
    subpath: "resources"
    dest: "resources"

  - action: download_github
    src: "mizterbonezzmusic/BonezzBangerz_PlugAndPlayRepo"
    ref: "main"
    subpath: "server-data/server.cfg"
    dest: "server.cfg"
