# Bonezz Bangerz – Full Addon (Remote Recipe w/ Admin Identifiers)
$schema: "https://raw.githubusercontent.com/tabarra/txAdmin-recipe-schemas/master/fxmanifest/recipe.yaml"

name: "Bonezz Bangerz – Full Addon"
version: "1.3.0"
author: "Bonezz"
description: |
  Remote recipe for Bonezz Bangerz server.
  Deploys bonezz_min and legacy Bonezz packs (Rx, UC Blips v2, UC Safehouses, Corrupt Cops).
  Adds identifiers as txAdmin admins; use ACE block in server.cfg for in-game GOD.

server: "Bonezz Bangerz"

tasks:
  - action: download_github
    src: "<YOUR-USERNAME>/BonezzBangerz_PlugAndPlayRepo"
    ref: "main"
    subpath: "resources/bonezz_min"
    dest: "resources/bonezz_min"

  - action: download_github
    src: "<YOUR-USERNAME>/BonezzBangerz_PlugAndPlayRepo"
    ref: "main"
    subpath: "resources/bonezz_rx_loader"
    dest: "resources/bonezz_rx_loader"

  - action: download_github
    src: "<YOUR-USERNAME>/BonezzBangerz_PlugAndPlayRepo"
    ref: "main"
    subpath: "resources/Bonezz_Rx_AllInOne_v3"
    dest: "resources/Bonezz_Rx_AllInOne_v3"

  - action: download_github
    src: "<YOUR-USERNAME>/BonezzBangerz_PlugAndPlayRepo"
    ref: "main"
    subpath: "resources/Bonezz_UC_Blips_v2"
    dest: "resources/Bonezz_UC_Blips_v2"

  - action: download_github
    src: "<YOUR-USERNAME>/BonezzBangerz_PlugAndPlayRepo"
    ref: "main"
    subpath: "resources/Bonezz_UC_Safehouses"
    dest: "resources/Bonezz_UC_Safehouses"

  - action: download_github
    src: "<YOUR-USERNAME>/BonezzBangerz_PlugAndPlayRepo"
    ref: "main"
    subpath: "resources/Corrupt_Cops"
    dest: "resources/Corrupt_Cops"

identifiers:
  - license:4576f02ddb6efa62a43154edd9367dec6e5271d1
  - xbl:2535445670033193
  - live:985160550934950
  - discord:679447894478028800
  - fivem:17437764
  - license2:4576f02ddb6efa62a43154edd9367dec6e5271d1

notes:
  - "Use server.cfg.example or paste docs/server_addon.cfg. Then add the ACE block for in-game GOD."
  - |
      ## === BONEZZ GOD (ACE) ===
      add_ace qbcore.god command allow
      add_principal qbcore.god group.admin
      add_principal qbcore.god qbcore.admin
      add_principal qbcore.admin qbcore.mod
      add_principal identifier.license:4576f02ddb6efa62a43154edd9367dec6e5271d1 qbcore.god
      add_principal identifier.license2:4576f02ddb6efa62a43154edd9367dec6e5271d1 qbcore.god
      add_principal identifier.discord:679447894478028800 qbcore.god
      add_principal identifier.xbl:2535445670033193 qbcore.god
      add_principal identifier.live:985160550934950 qbcore.god
      add_principal identifier.fivem:17437764 qbcore.god

      ensure bonezz_min
      # optional:
      # ensure Bonezz_Rx_AllInOne_v3
      # ensure Bonezz_UC_Blips_v2
      # ensure Bonezz_UC_Safehouses
      # ensure Corrupt_Cops
